name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: valerienierenberg/metrics@main
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          base: no
          plugin_introduction: no
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitation
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_skipped: metrics, valerienierenberg.github.io
          plugin_habits: yes
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }} # Optional but recommended
          plugin_pagespeed_detailed: yes                         # Print detailed audit metrics
          plugin_pagespeed_screenshot: yes                        # Display a screenshot of your website
          plugin_pagespeed_url: .user.website                    # Website to audit (defaults to your GitHub linked website)
