# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: valerienierenberg/metrics@main
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: valerienierenberg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Chicago
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_skipped: metrics, valerienierenberg.github.io
          # plugin_pagespeed: yes
          # plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }} # Optional but recommended
          # plugin_pagespeed_detailed: yes                         # Print detailed audit metrics
          # plugin_pagespeed_screenshot: yes                        # Display a screenshot of your website
          # plugin_pagespeed_url: .user.website                    # Website to audit (defaults to your GitHub linked website)
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 4
